-- 1. H2.bat 을 사용해 H2로 접속
-- 2. jdbc:h2:~/test 로 DB테이블 만들고, Home에서 ~/test.mv.db 확인하고, jdbc:h2:tcp://localhost/~/test으로 여러군데에서 접근가능
-- 3. 본격적으로 DB 테이블 사용한다
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);